# Generated by Django 5.0.7 on 2024-09-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_practicesection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='learn',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='category',
        ),
    ]
