# Generated by Django 5.0.7 on 2024-07-30 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_grammarsubcategory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('author', models.CharField(max_length=90)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learn',
            },
        ),
        migrations.CreateModel(
            name='PracticeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('instruction', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_section',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('option_one', models.CharField(blank=True, max_length=255)),
                ('option_two', models.CharField(blank=True, max_length=255)),
                ('option_three', models.CharField(blank=True, max_length=255)),
                ('feedback', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('practice_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.practicesection')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
        migrations.RemoveField(
            model_name='grammarblog',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='grammarblogassessment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='grammarsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grammartestsection',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='grammartest',
            name='test_section',
        ),
        migrations.DeleteModel(
            name='Vocab',
        ),
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GrammarBlog',
        ),
        migrations.DeleteModel(
            name='GrammarBlogAssessment',
        ),
        migrations.DeleteModel(
            name='GrammarCategory',
        ),
        migrations.DeleteModel(
            name='GrammarSubCategory',
        ),
        migrations.DeleteModel(
            name='GrammarTest',
        ),
        migrations.DeleteModel(
            name='GrammarTestSection',
        ),
    ]
