# Generated by Django 5.0.7 on 2024-09-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_learn_practicesection_questions_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesection',
            name='learn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.learn'),
            preserve_default=False,
        ),
    ]
