# Generated by Django 5.0.7 on 2024-09-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_practicesection_learn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicesection',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='practicesection',
            old_name='learn',
            new_name='learn_id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='practice_section',
            new_name='practice_section_id',
        ),
        migrations.RenameField(
            model_name='testdata',
            old_name='category',
            new_name='category_id',
        ),
    ]
